# Generated by Django 3.1.2 on 2020-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0002_auto_20201030_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='landArea',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='地坪(平方公尺)'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landAreaDepth',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地深度'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landAreaWidth',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地寬度'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='所有持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='個人持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landPresentValue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='土地現值'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landRemarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landTotalArea',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='地坪總面積'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='landUrl',
            field=models.URLField(blank=True, null=True, verbose_name='謄本'),
        ),
    ]
