# Generated by Django 3.1.2 on 2020-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0002_auto_20201119_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseAcceptingAuthorityTownship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鄉鎮區里'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseApplyAcrossInstitutions',
            field=models.BooleanField(default=False, verbose_name='跨所申請'),
        ),
        migrations.AlterField(
            model_name='objectbuild',
            name='objectBuildAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='objectbuild',
            name='objectBuildScorReasonA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='加成原因A'),
        ),
    ]
