# Generated by Django 3.1.2 on 2020-11-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0003_auto_20201120_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorFloor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)'),
        ),
    ]
