# Generated by Django 3.1.2 on 2020-11-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0004_auto_20201120_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='city_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
