# Generated by Django 3.1.2 on 2020-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0005_township_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='finalDecision',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='regionalHead',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='regionalHeadDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='簽核日期'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='regionalHeadWorkArea',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務轄區'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='subSigntrueA',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='subSigntrueB',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='subSigntrueDateA',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='簽核日期'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='subSigntrueDateB',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='簽核日期'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='subSigntrueWorkAreaA',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務轄區'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='subSigntrueWorkAreaB',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務轄區'),
        ),
    ]
