# Generated by Django 3.1.2 on 2020-12-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0006_auto_20201209_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalDecision',
        ),
    ]
