# Generated by Django 3.1.2 on 2020-12-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0007_delete_finaldecision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectbuild',
            name='objectBuildStatus',
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='objectBuildGoogleMap',
            field=models.URLField(blank=True, null=True, verbose_name='Google地圖'),
        ),
    ]
