# Generated by Django 3.1.2 on 2020-11-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0012_finaldecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldecision',
            name='regionalHeadWorkArea',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務轄區'),
        ),
    ]
