# Generated by Django 3.1.2 on 2020-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0013_finaldecision_regionalheadworkarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldecision',
            name='subSigntrueWorkAreaA',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務轄區'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='subSigntrueWorkAreaB',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務轄區'),
        ),
    ]
