# Generated by Django 3.1.2 on 2020-11-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0016_auto_20201115_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorAlley',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='弄'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorBirthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorBuildHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物所有持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorBuildHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物個人持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorCity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorFloor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorIdentityCard',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='身分証或統一編號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorLandHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地所有持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorLandHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地個人持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorLane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='巷'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorLocalPhone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='市話'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorMobilePhone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorNeighbor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorSection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='段'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorStreet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='街路'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorTownship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鄉鎮區'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorVillage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='村里'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorAlley',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='弄'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorBirthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorBuildHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物所有持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorBuildHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物個人持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorCity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorFloor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorIdentityCard',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='身分証或統一編號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorLandHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地所有持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorLandHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地個人持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorLane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='巷'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorLocalPhone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='市話'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorMobilePhone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorNeighbor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorSection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='段'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorStreet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='街路'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorTownship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鄉鎮區'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorVillage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='村里'),
        ),
    ]
