# Generated by Django 3.1.2 on 2020-11-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0017_auto_20201115_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxCoOwnerMatch',
            field=models.BooleanField(default=True, verbose_name='共有人一致'),
        ),
    ]
