# Generated by Django 3.1.2 on 2020-11-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0018_yfcase_yfcasedeedtaxcoownermatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxClient',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅委託人'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxClosingNewsletter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅結案簡訊'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxDeclarationDate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅申報日期'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxEstablishmentDate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅建立日期'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxHouseTaxRegistrationNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='房屋稅籍編號區'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxReclaimMethod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅領回方式'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxRemarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅備註'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxReportAttached',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='契稅報附聯'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxTransferPrice',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='契稅移轉價格'),
        ),
    ]
