# Generated by Django 3.1.2 on 2020-11-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0019_auto_20201116_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseDeedtaxAgent',
        ),
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseDeedtaxDateOfCause',
        ),
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseDeedtaxReasonForRegistration',
        ),
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseDeedtaxRegistrationNote',
        ),
    ]
