# Generated by Django 3.1.2 on 2020-11-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0021_auto_20201116_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseDeedtaxCreditorBirthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseDeedtaxDebtorBirthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
