# Generated by Django 3.1.2 on 2020-11-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0022_auto_20201116_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferArea1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='移轉情形-面積(平方公尺)-1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferArea2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='移轉情形-面積(平方公尺)-2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferArea3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='移轉情形-面積(平方公尺)-3'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferArea4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='移轉情形-面積(平方公尺)-4'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferArea5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='移轉情形-面積(平方公尺)-5'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferArea6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='移轉情形-面積(平方公尺)-6'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferLevel1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-層次1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferLevel2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-層次2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferLevel3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-層次3'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferLevel4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-層次4'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferLevel5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-層次5'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferLevel6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-層次6'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicBuildingNumber1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-公設建號1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicBuildingNumber2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-公設建號2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicBuildingNumber3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-公設建號3'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicBuildingNumber4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-公設建號4'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicHoldings1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-持分比例1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicHoldings2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-持分比例2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicHoldings3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-持分比例3'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferPublicHoldings4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-持分比例4'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferStructure1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-構造1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferStructure2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-構造2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferStructure3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-構造3'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferStructure4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-構造4'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferStructure5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-構造5'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxBuildingTransferStructure6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉情形-構造6'),
        ),
    ]
